# Generated by Django 4.2.6 on 2023-10-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('shop', '0002_delayreport_order_alter_delayreport_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.vendor'),
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
